### PR TITLE
flanneld: adds basic health-check endpoint

### PR DESCRIPTION
**Pull request by genevievelesperance**
This begins to address #616.

We can follow up later with a richer health-check that captures connectivity to etcd.

cc: @rosenhouse

### CODE REVIEW

**Comment by andyxning** [comment]
Any updates on this?

**Comment by genevievelesperance** [comment]
@rosenhouse ^^^

**Comment by andyxning** [comment]
@genevievelesperance Why you close this PR? Is healthcheck functionality available already?

**Comment by rosenhouse** [comment]
@andyxning Our team has recently decided to stop using flannel and to build something different.  So we won't be working on a flannel healthcheck. 

Feel free to open a new PR with this code or something similar.  We just won't be shepherding it.

**Pull request closed without merging**
