### PR TITLE
Updating code.google.com/p/... dependencies

### LINKED ISSUE #406: outdated dependencies on code.google.com
When trying to use ``godep`` to restore dependencies, it fails to do so because of references to code.google.com dependencies (which was shutdown).

```
godep: error downloading dep (code.google.com/p/goauth2/compute/serviceaccount): unable to detect version control system for code.google.com/ path
godep: error downloading dep (code.google.com/p/goauth2/oauth): unable to detect version control system for code.google.com/ path
godep: error downloading dep (code.google.com/p/google-api-go-client/compute/v1): unable to detect version control system for code.google.com/ path
godep: error downloading dep (code.google.com/p/google-api-go-client/googleapi): unable to detect version control system for code.google.com/ path
```

### PR DESCRIPTION
**Pull request by davidsiefert**
Project hosting provider code.google.com was shutdown beginning of this year.  This updates code.google.com dependencies.  Minor changes were required for oauth in GCE module.

Fixes #406

### CODE REVIEW

**Comment by davidsiefert** [comment]
This touches oauth of GCE.  I do not have a GCE account, nor any GCE experience.  Would someone be able to help out and verify this still works in GCE?  Thanks!!  I am also a Golang+Godep newb.  I do not know what I am doing.  Please someone save me from my mistakes.

**Comment by tomdee** [comment]
I would like to merge this, but I need to coordinate it with #438

**Comment by davidsiefert** [comment]
omg! omg! really? i almost gave up on this.  thanks!!

**Comment by kkirsche** [comment]
@tomdee what kind of testing do you need for this?

**Pull request closed without merging**
