### PR TITLE
Remove unexpected route from route list

### PR DESCRIPTION
**Pull request by chenchun**

### CODE REVIEW

**Comment by tomdee** [comment]
thanks @chenchun this looks like a good fix. Before I merge it, can you share a little bit of information on how you hit this and how you've tested the fix. Ideally there would be an automated test case for this too, would that be possible to add?

**Comment by chenchun** [comment]
Found this bug through reading the code. I've added an unit test. PTAL

**Comment by tomdee** [comment]
Looks good thanks. You'll need to update the Makefile too though, the  TEST_PACKAGES variable needs to include backend/hostgw

**Comment by chenchun** [comment]
Previous tests fails with
```
--- FAIL: TestRouteCache (0.00s)
	hostgw_network_test.go:43: operation not permitted
```

Updated Makefile to makes use of `docker run` to give go test NET_ADMIN capability.

**Comment by tomdee** [comment]
This does mean that Docker is needed for running the unit tests, but I think that's OK now since the end to end tests need Docker too.

**Pull request merged**
