### PR TITLE
Remove glog in favor of capnslog.

### LINKED ISSUE #295: Move away from glog logger
glog is overly verbose and always prints a timestamp. The logger should detect if it runs under journald and not log the timestamp in that case.

### PR DESCRIPTION
**Pull request by tshprecher**
Fixes #295.

This commit replaces glog with capnslog.

Before change:

> $ /tmp/flanneld_master 
I0325 23:31:34.385810 28708 main.go:120] Installing signal handlers
I0325 23:31:34.386273 28708 manager.go:133] Determining IP address of default interface
I0325 23:31:34.386766 28708 manager.go:163] Using 192.168.0.102 as external interface
I0325 23:31:34.387078 28708 manager.go:164] Using 192.168.0.102 as external endpoint
E0325 23:31:34.388088 28708 network.go:106] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
E0325 23:31:35.389913 28708 network.go:106] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
E0325 23:31:36.391217 28708 network.go:106] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
E0325 23:31:37.392842 28708 network.go:106] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
E0325 23:31:38.394152 28708 network.go:106] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured

After change:
> $ ./bin/flanneld 
2016-03-25 23:33:02.039974 I | backend: Register: alloc
2016-03-25 23:33:02.040642 I | backend: Register: aws-vpc
2016-03-25 23:33:02.041219 I | backend: Register: gce
2016-03-25 23:33:02.041606 I | backend: Register: host-gw
2016-03-25 23:33:02.042074 I | backend: Register: udp
2016-03-25 23:33:02.042446 I | backend: Register: vxlan
2016-03-25 23:33:02.043034 I | main: Installing signal handlers
2016-03-25 23:33:02.043500 I | network: Determining IP address of default interface
2016-03-25 23:33:02.044112 I | network: Using 192.168.0.102 as external interface
2016-03-25 23:33:02.044397 I | network: Using 192.168.0.102 as external endpoint
2016-03-25 23:33:02.045418 E | network: failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
2016-03-25 23:33:03.047685 E | network: failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
2016-03-25 23:33:04.048755 E | network: failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
2016-03-25 23:33:05.050264 E | network: failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
2016-03-25 23:33:06.052024 E | network: failed to retrieve network config: client: etcd cluster is unavailable or misconfigured

The original ticket mentioned simplifying the format when running with journald. I did not include that change, just the migration from glog to capnslog. I'm not sure what the right approach is for that. I'm new to the way things are done with the CoreOS stack and am not confident in my local setup yet to make this change correctly.

I added capnslog to the Godeps, but I couldn't find out a clean way to add this single dependency without manually copying the snapshot of the package and tweaking the import to correctly point to go-systemd/journal. (Yes, I'm aware of the message "Please do not edit." in Godeps/Readme. I bugs me that I couldn't find a way with godep.). Please let me know if I did this incorrectly and I will remedy.

### CODE REVIEW

**Comment by steveeJ** [comment]
On first sight I see that the filename:line information is gone which I personally prefer. Why would we chose the PR over the existing logging?

**Comment by tshprecher** [comment]
@steveeJ the difference is logging by package instead of file. It's been a while since I took a look at this, but I believe other coreOS projects use the PackageLogger. This PR is a matter of making the projects consistent.

**Comment by steveeJ** [comment]
@tshprecher 
My impression is that `https://godoc.org/github.com/Sirupsen/logrus is now the preferred logging package. This PR would now need a rebase and rework due to the recent switch from Godep to glide. Would you be open to switching to logrus or should we close this and someone else takes over?

In any way, thanks for the effort put into this!

**Comment by tshprecher** [comment]
Yeah, the godep dependency was one of the reasons why this PR has been sitting around for so long. Thanks for reaching out, but you can hand this off to someone else.

**Comment by kkirsche** [comment]
@steveej So is the goal only to replace the logging or is to also normalize logging style as with other packages?

**Comment by tomdee** [comment]
Closing as this requires significant rework

**Comment by kkirsche** [comment]
May I ask what that actually means? It sounds like it just isn't prioritized due to work, -'d should stay open. It doesn't make sense to me at least with what you've said that this is really something that shouldn't be done thus needing to be closed.

**Comment by tomdee** [comment]
@kkirsche The original issue is still open, it's just that this PR doesn't seem like it's going anywhere so I'm not sure what value it brings leaving it open. The current flavor of the month seems to be logrus so that's probably a better project to use to replace glog.

**Comment by kkirsche** [comment]
Ah, ok. Thanks for explaining that @tomdee — that logic makes more sense to me

**Pull request closed without merging**
