### PR TITLE
Enable e2e tests for multiarch

### PR DESCRIPTION
**Pull request by mkumatag**
## Description
This PR is for enabling e2e tests to run on different architectures like arm64 and ppc64le

## Todos
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by tomdee** [comment]
@mkumatag Looks fine in principle but it will need rebasing on top of the test refactoring that just got merged to master.

**Comment by mkumatag** [comment]
Sure will rebase it...

**Comment by mkumatag** [comment]
submitted via different PR - https://github.com/coreos/flannel/pull/845

**Pull request closed without merging**
