### PR TITLE
Add mk-docker-opts script to write Dockerd opts

### PR DESCRIPTION
**Pull request by eyakubovich**
Output FLANNEL_IPMASQ to subnet.env with value of --ip-masq.
dist/mk-docker-opts converts subnet.env into Docker daemon
options.

### CODE REVIEW

**Comment by eparis** [comment]
I'd love for this to end in .sh, like most scripts.  no big deal.  I made a couple of editions (addressed #244 in the process I think...)

particularly the stuff around "combined_opts"

http://pkgs.fedoraproject.org/cgit/flannel.git/commit/?id=8d0e6c275d6eb3c779d4f3f5e29b84dd865796b2

**Comment by eyakubovich** [comment]
@eparis I renamed to have .sh and changed the DOCKER_OPTS to DOCKER_NET_OPTS.

**Comment by eparis** [comment]
-k and the "combined_opts" let me define on the command line what I wanted to use. (fedora uses DOCKER_NETWORK_OPTIONS)

I don't know how to give a patch against a PR making that name mutable from the command line.

**Comment by eparis** [comment]
wrong link last time.  so sorry!

http://pkgs.fedoraproject.org/cgit/flannel.git/commit/?id=3b954b37fa5e65278a60e1945d3180c859a13be3

**Comment by eyakubovich** [comment]
@eparis Changes from your diff merged.

**Comment by eparis** [comment]
LGTM

**Comment by eparis** [comment]
except we just undid you change from DOCKER_OPTS to DOCKER_NET_OPTS

mind you these DOCKER_OPTS will include the other DOCKER_OPTS, so maybe you don't care.

**Comment by eyakubovich** [comment]
@eparis I know but now there's -k to override so I don't really care.

**Pull request merged**
