### PR TITLE
VXLAN static forwarding

### PR DESCRIPTION
**Pull request by titanous**
This removes the complicated monitoring code and replaces it with three network configuration entries for each subnet lease that cause the packets to end up in the right place:

- A route pointing all traffic to the subnet via a gateway that is the IP of the flannel interface on the target host.
- A forwarding database entry that maps the network-routable IP address of the target host to the MAC address of the flannel interface on the same host.
- An ARP table entry mapping the IP address of the flannel interface on the target host to the MAC address of the same interface.

### CODE REVIEW

**Comment by eyakubovich** [comment]
@titanous we'd like to merge this commit but need to make sure the stale entries are removed on start. Do you mind if we take these commits, rebase them and add the required functionality? Your commit (with you as an author) will be retained.

**Comment by titanous** [comment]
Go for it. We've been using this in Flynn since I opened the PR with no trouble.

**Comment by eyakubovich** [comment]
Thanks. Great to hear that it works well.

**Comment by eyakubovich** [comment]
Obsoleted by https://github.com/coreos/flannel/pull/191

**Pull request closed without merging**
