### PR TITLE
Compile flanneld statically

### PR DESCRIPTION
**Pull request by luxas**
Fixes: #389

### CODE REVIEW

**Comment by luxas** [comment]
Ping @philips

**Comment by glevand** [comment]
It looks OK, but it would be more flexible if the static link was set by a variable which could be turned off.    Maybe something like:

    STATIC_LINK=...
    GLDFLAGS="... ${STATIC_LINK})"

I'll test next time I build flannel.

**Comment by luxas** [comment]
@glevand Updated. Merge if you think it's fine

**Comment by luxas** [comment]
Please merge this. Another thing, when will a new release be out?

**Comment by glevand** [comment]
@luxas I added static link to my buildroot flannel package https://github.com/glevand/buildroot--buildroot/commits/master.  I'm hoping this will eventually replace the old flannel build system.

Right now there is no flannel maintainer, so we just need to wait until a new maintainer is found.

**Comment by luxas** [comment]
@glevand Yeah, I see no one is actively working on it.

@philips Who's gonna take over? From an outside perspective it's a bit strange for a project like this not to have a maintainer. I'm absolutely not blaming anyone, just saying that would be great if a such great piece of code like this is maintained :)

**Comment by luxas** [comment]
@tomdee @steveeJ Please take a look

**Comment by luxas** [comment]
Oh, didn't see #439
Closing in favor for that one.

**Pull request closed without merging**
