### PR TITLE
remote: close response body during watch()

### PR DESCRIPTION
**Pull request by jonboulle**
From eyeballing #337 this might be the culprit.
/cc @eyakubovich @ssergiienko

### CODE REVIEW

**Comment by eyakubovich** [comment]
Regardless, It's a good bug to catch.

**Comment by eyakubovich** [comment]
LGTM

**Comment by ravilr** [comment]
@eyakubovich is there a release coming soon that this is going to be part of? Thanks.

**Comment by eyakubovich** [comment]
@jonboulle I was hoping that it'll go into the next release (0.6) but it looks like that one is still a bit out and, more importantly, might not be too stable due to lots of turmoil in the codebase lately.  Therefore, I will do 0.5.4 this week with cherry-picked commits from the master.

**Pull request merged**
