### PR TITLE
 Enable host to local pod connectivity in Windows VXLAN

### PR DESCRIPTION
**Pull request by ksubrmnn**
## Description

This PR adds a Host Route policy to the network in Windows VXLAN. This allows a host to communicate with pods on that host. Windows hosts still do not have connectivity with pods running on remote hosts when running VXLAN.
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Enable local host to local pod connectivity in Windows VXLAN
```

### CODE REVIEW

**Comment by ksubrmnn** [comment]
@madhanrm

**Comment by ksubrmnn** [comment]
Do not merge this yet. Just creating this PR for now, I haven't super strictly validated it yet

**Comment by ksubrmnn** [comment]
@madhanrm @rajatchopra  this is ready to be reviewed and merged

**Comment by madhanrm** [comment]
lgtm

**Comment by ksubrmnn** [comment]
@rajatchopra

**Comment by loganhz** [comment]
Hi @ksubrmnn , 

If a kubernetes svc pointing to the node internal IP in VXLAN mode,  we cannot access the VIP in Windows containers.

It means users cannot access Kubernetes API server in Windows containers.

We have filed an issue in Kubernetes repo https://github.com/kubernetes/kubernetes/issues/79359

Is it expected?

**Pull request merged**
