### PR TITLE
Add NET_RAW capability

### PR DESCRIPTION
**Pull request by kubealex**
Adding NET_RAW capability allows flannel to become compatible with k8s using cri-o as runtime.

Otherwise, the pods remain looping in iptables rules creation.
Solves:
https://github.com/coreos/flannel/issues/1300

### CODE REVIEW

**Comment by kubealex** [comment]
bump!

**Comment by kubealex** [comment]
@rajatchopra is there a way to run tests again? This compromises the compatibility with cri-o runtime

**Comment by luthermonson** [comment]
@kubealex the gofmt issue is fixed in master now if you want to rebase.

**Comment by kubealex** [comment]
Closing this, I reopened #1325  to clean up the commits.

**Pull request closed without merging**
