### PR TITLE
Use "docker manifest" to publish multi-arch Docker images

### PR DESCRIPTION
**Pull request by hakman**
## Description
Multi-arch Docker images are very common these days and allow simplify Kubernetes manifests and deployments in general.
At the moment, flannel publishes the AMD64 image both as $REPO:$TAG and $REPO:$TAG-amd64. Instead of duplicating the AMD64 image, the $REPO:$TAG could be a Docker manifest.

This would allow to de-duplicate a lot the content of https://github.com/coreos/flannel/blob/v0.12.0/Documentation/kube-flannel.yml in a future PR.

Fixes: #1116 

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Release note

## Release Note

```release-note
Create multi-arch image instead of duplicating the AMD64 image
```

### CODE REVIEW

**Comment by rajatchopra** [comment]
Aha! Very useful. About time.
Will test and queue it up for merge.
Thanks.

**Comment by hakman** [comment]
Thanks @rajatchopra. I added a small extra to cover `flannel-git` also. Will send another PR to squash the flannel manifest later this week.

**Comment by electrocucaracha** [comment]
Hey there, I have a [Kubespray's PR](https://github.com/kubernetes-sigs/kubespray/pull/6166) that is targeting to add Flannel Multi-Arch there but this change will definitely help on that.  Hopefully this change gets merged soon.

**Comment by hakman** [comment]
@rajatchopra any chance this can make it into v0.13.0?

**Comment by Oats87** [comment]
LGTM

**Comment by hakman** [comment]
Thanks @rajatchopra :)

**Pull request merged**
