### PR TITLE
EnableNonPersistent flag for Windows Overlay networks

### PR DESCRIPTION
**Pull request by ksubrmnn**
## Description

This PR adds the EnableNonPersistent flag for Windows Overlay networks. This ensures that the network will be cleaned up upon reboot. 
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by ksubrmnn** [comment]
@madhanrm

**Comment by ksubrmnn** [comment]
@rajatchopra looks like Travis is missing `wireguard-tools` so it can't build. Don't think the failure has to do with my PR

**Comment by ksubrmnn** [comment]
@madhanrm @rajatchopra

**Comment by madhanrm** [comment]
LGTM

**Comment by dineshgovindasamy** [comment]
@rajatchopra ping?

**Pull request merged**
