### PR TITLE
Add cli args for etcd basic auth

### PR DESCRIPTION
**Pull request by shanegibbs**
Adds support for `--etcd-username` and `--etcd-password` args.

### CODE REVIEW

**Comment by philips** [comment]
this seems fine

**Comment by dcbw** [comment]
Seems fine to me too

**Comment by wikiwi** [comment]
+1 Hope this will be merged soon.

**Comment by shanegibbs** [comment]
@philips, what would the process to get this merged be? Anything I can help with?

**Comment by shanegibbs** [comment]
Looks like the etcd client v3 won't be using basic auth

**Comment by tomdee** [comment]
Small, simple and potentially useful change. We'll cross the etcd v3 bridge when we get to it. Merging.

**Pull request merged**
