### PR TITLE
Improve VXLAN performance by udpcsum

### PR DESCRIPTION
**Pull request by okamototk**
Add udp outer checksum to enable GSO/GRO with VXLAN.
This improve VXLAN performance and less CPU usage at
receiver.

The PR include following netlink commit.

https://github.com/vishvananda/netlink/commit/06ac83f14ae36fe70da4bb70fdd01b071821af53

If update netlink, you don't need netlink's modification.

### CODE REVIEW

**Comment by jonboulle** [comment]
can you bump the Godep for netlink instead of manually patching it here? thanks

**Comment by okamototk** [comment]
I'm new for godep. Do you mean I should rebase netlink? 
How can I rebase netlink with godeps?

**Comment by jonboulle** [comment]
Check out the instructions in this page:
https://github.com/coreos/docs/blob/master/golang/godep.md#update-an-existing-dependency

**Comment by philips** [comment]
@okamototk did you get a chance to bump this? 

Also, is UDPCSum = true a safe default?

**Comment by jeremyeder** [comment]
Where is the kernel support for this ?  Ed Cree's patch set isn't even in net-next afaict...

**Comment by dcbw** [comment]
@jeremyeder it looks like this PR only requires IFLA_VXLAN_UDP_CSUM and that should be in 3.16+ kernels.  Previous kernels will likely return an error since I think unrecognized netlink attributes fail validation.  So the flannel code should probably be updated to retry without UDPCsum on failure.

**Comment by tomdee** [comment]
Does anyone have any benchmarks for how much of a performance benefit this provides?

**Comment by tomdee** [comment]
@okamototk Are you still interested in getting this PR merged? If so, please rebase, thanks.

**Comment by tomdee** [comment]
Looks like udpcsum is already being used:
```
ip  -d  link  show  flannel.1
5: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether c2:cb:20:31:38:1c brd ff:ff:ff:ff:ff:ff promiscuity 0 
    vxlan id 1 local 172.17.4.201 dev eth1 srcport 0 0 dstport 8472 nolearning ageing 300 udpcsum addrgenmode eui64 ```

**Pull request closed without merging**
