### PR TITLE
prevent failed builds from being shadowed by old working builds

### PR DESCRIPTION
**Pull request by jayunit100**
Minor put important improvement to prevent binary failed builds shadowed by old builds

### CODE REVIEW

**Comment by eyakubovich** [comment]
A failed build will be vocal so you know it has failed. It is very typical to not delete a binary before starting a build. Manual deletion also impedes edit-compile-run cycle by adding an extra step.

Can you speak to how this has been a problem for you?

**Comment by jayunit100** [comment]
testing th e binary , after build - leads to testing an old artifact.  so iits quite misleading imo... but i see your point to.

**Comment by eyakubovich** [comment]
We can add a Makefile with `clean` target (and others that forward to our bash scripts) but it maybe simpler to just add a simple `clean` script to wipe `./bin/flanneld`.

**Comment by jayunit100** [comment]
Yup Makefile is probably the safest bet.  I can look at it this wk.  good feedback thanks ;

**Comment by philips** [comment]
Hello @jayunit100 I am going to close this out. Please re-open if you have a chance to work on it.

**Pull request closed without merging**
