### PR TITLE
apiVersion: Beta -> Stable

### PR DESCRIPTION
**Pull request by RaSla**
* rbac.authorization.k8s.io/v1beta1 -> rbac.authorization.k8s.io/v1
* beta.kubernetes.io/arch -> kubernetes.io/arch

## Todos
- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by arasananbu** [comment]
LGTM. support for Kubernetes 1.16. Will not work for <1.16. Are we changing the support to k8s >= 1.16, Then should be release noted.

Ref: https://kubernetes.io/docs/setup/release/notes

**Comment by rajatchopra** [comment]
We need to have another file for <1.16 if there is a split here. @RaSla can you copy the older one with an extension like kube-flannel-beta.yaml?

**Comment by RaSla** [comment]
I have saved old file as **kube-flannel-before-1.16.yml**.
And added "**"cniVersion": "0.3.1",**" into **kube-flannel.yml** for correct k8s-1.16 support

**Comment by rajatchopra** [comment]
@RaSla Please update the PR. cniVersion was updated to 0.20 already, so maybe do not include that as part of this PR.

**Comment by RaSla** [comment]
* Synced **Documentation/kube-flannel.yml** with Master (cniVersion, nodeAffinity)
* Patched versions: Beta -> Stable for **nodeAffinity** block

**Pull request closed without merging**
