### PR TITLE
Update go-etcd to v0.4.6 with PR #195 to fix the connection leak

### PR DESCRIPTION
**Pull request by lvlv**
Sorry, I accidentally deleted my last branch https://github.com/coreos/flannel/pull/144, have to create a new PR instead :(

### CODE REVIEW

**Comment by lemenkov** [comment]
Subscribing.

**Comment by eyakubovich** [comment]
LGTM. Thank you for tracking this down and fixing it.

**Comment by yichengq** [comment]
@eyakubovich go-etcd is not tagged correctly, and current master is only for etcd 2.0. The go-etcd for 0.4 is at https://github.com/coreos/go-etcd/commits/release-0.4. I can retag it and cherry-pick the changes that lvlv makes into release-0.4 branch.

**Comment by eyakubovich** [comment]
@yichengq great, please cherry-pick and I'll update flannel.

**Pull request merged**
